### PR TITLE
Add census-rm-case-api deployment

### PR DESCRIPTION
**Pull request by liamtoozer**
# Motivation and Context

This change adds the census-rm-case-api service to the Concourse deployment pipeline.

# What has changed

* ci-kubernetes-pipeline.yml

# How to test?

fly the pipeline and check the deployment is successful and the acceptance tests pass.

# Links

https://trello.com/c/Tg697scy/633-rmc-139-provide-case-look-up-for-cc-13#

### CODE REVIEW

**Comment by liamtoozer** [comment]
[RMC-139 Provide case look up for CC (13)](https://trello.com/c/Tg697scy/633-rmc-139-provide-case-look-up-for-cc-13)

**Review by AdeHarrison — APPROVED** [review]
LGTM

**Review by NickGrantX — APPROVED** [review]
LGTM 👍

**Comment by liamtoozer** [comment]
Closed as initial commit was 'unverified', so unable to merge. Will open another PR...

**Pull request closed without merging**
